version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "15672:15672"
    - "5672:5672"
    - "61613:61613"
    - "15674:15674"
    volumes:
    - ./enabled_plugins:/etc/rabbitmq/enabled_plugins